version: '3'
services:
  db:
    build: ./mysql
    container_name: Mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
