version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: Nginx
    ports:
      - "80:80"
    volumes:
      #- .:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./web/static:/static
    depends_on:
      - web
  db:
    #image: mysql
    build: ./mysql
    container_name: Mysql
    ports:
      - "3306:3306"
    #volumes:
      #- ./db:/var/lib/mysql
      #- ./mysql/sql:/docker-entrypoint-initdb.d
    environment:
      #- MYSQL_DATABASE=django
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
  web:
    build: ./web
    container_name : IMF_Mointer
    restart: always
    #command: python manage.py runserver 0.0.0.0:8000
    command: bash -c "python manage.py makemigrations && python manage.py migrate && mysql -udjango -pdjango -h db -P 3306 < /app/config/sql/1-modified_django.sql && gunicorn dashboard.wsgi -b 0.0.0.0:80"
    volumes:
      - .:/app/web
      - ./web/static:/static
    expose:
      - "80"
    depends_on:
      - db
