version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: Nginx
    ports:
      - "80:8080"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./web/static:/static
    depends_on:
      - web
  db:
    build: ./mysql
    container_name: Mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=django
      - MYSQL_PASSWORD=django
  web:
    build: ./web
    container_name : IMF_Mointer
    restart: always
    command: bash -c "python manage.py makemigrations && python manage.py migrate && mysql -udjango -pdjango -h db -P 3306 < /app/config/sql/1-modified_django.sql && gunicorn dashboard.wsgi -b 0.0.0.0:8080"
    volumes:
      - .:/app/web
      - ./web/static:/static
    expose:
      - "80"
    depends_on:
      - db
