# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trigger_status',
            fields=[
                ('rowcreatedatetime', models.DateTimeField(auto_now_add=True)),
                ('rowoperatedatetime', models.DateTimeField(auto_now=True)),
                ('triggerid', models.IntegerField(primary_key=True, serialize=False)),
                ('triggerstatus', models.IntegerField()),
                ('triggername', models.CharField(max_length=300, null=True)),
                ('itemid', models.IntegerField()),
                ('applicationname', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
