# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger_status',
            old_name='triggerstatus',
            new_name='triggervalue',
        ),
    ]
