# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0002_auto_20170511_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsystemname', models.CharField(max_length=20)),
                ('subsystemstatus', models.IntegerField()),
                ('triggername', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
