# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0004_auto_20170606_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsystem_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationname', models.CharField(max_length=20)),
                ('triggervalue', models.IntegerField()),
            ],
            options={
                'db_table': 'zabbix_subsystemname',
                'managed': False,
            },
        ),
    ]
