# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0006_delete_subsystem_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger_status',
            name='eventid',
            field=models.IntegerField(null=True),
        ),
    ]
