# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix', '0007_trigger_status_eventid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trigger_status',
            old_name='eventid',
            new_name='latesteventid',
        ),
    ]
